spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobios_coupon_generate
    username: root
    password: 2367
  jpa:
    hibernate:
      ddl-auto: create

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem